Revert "Remove remaining mentions of gflags"
This reverts commit 90ce84e1d3201103823a6c615ccbed9e84b1c2c4.

Reason for revert: Compilation failure on webrtc.fyi
(error: no member named 'GetLogToDebug' in 'rtc::LogMessage')

Original change's description:
> Remove remaining mentions of gflags
> 
> Bug: webrtc:7644
> Change-Id: I1906419e597fe6f80247e8def78c958f3759ba00
> Reviewed-on: https://webrtc-review.googlesource.com/2687
> Commit-Queue: Oleh Prypin <oprypin@webrtc.org>
> Reviewed-by: Henrik Kjellander <kjellander@webrtc.org>
> Cr-Commit-Position: refs/heads/master@{#19938}

TBR=kjellander@webrtc.org,oprypin@webrtc.org

Change-Id: I0e4c7191a405e45c85d007bc385bee5de5b4d323
No-Presubmit: true
No-Tree-Checks: true
No-Try: true
Bug: webrtc:7644