Revert of Cleanup webrtc/base/base.gyp (patchset #2 id:80001 of https://codereview.webrtc.org/1859803002/ )
Reason for revert:
For some odd reason this breaks chromium.webrtc.fyi bots:
../../third_party/webrtc_overrides/webrtc/base/win32socketinit.cc:13:2: error: "Only compile this on Windows"
#error "Only compile this on Windows"
 ^
1 error generated.

https://build.chromium.org/p/chromium.webrtc.fyi/builders/Mac%20Builder/builds/11515/steps/compile/logs/stdio
https://build.chromium.org/p/chromium.webrtc.fyi/builders/Linux%20Builder/builds/4650/steps/compile/logs/stdio

Original issue's description:
> Cleanup webrtc/base/base.gyp
>
> * Remove all source exclusions since they make the file very hard to
>   read and heavily increases the risk for mistakes.
> * Don't compile the openssl* sources if use_openssl==0.
> * Move platform specific sources into conditional includes to make it
>   easier to verify a 1:1 mapping with BUILD.gn (since GN doesn't support
>   automatic detection of platform specific sources based on filenames).
> * Add missing sources for the GN build.
> * Reorder some blocks to make GYP vs GN mapping match.
>
> BUG=webrtc:4256
> R=perkj@webrtc.org, torbjorng@webrtc.org
>
> Committed: https://crrev.com/47f33cb28ffb0fa0f053ae0aa0086e11f85bf444
> Cr-Commit-Position: refs/heads/master@{#12235}

TBR=perkj@webrtc.org,torbjorng@webrtc.org
# Not skipping CQ checks because original CL landed more than 1 days ago.
BUG=webrtc:4256
NOTRY=True

Review URL: https://codereview.webrtc.org/1856323003