Update patch set 3
Patch Set 3:

> Patch Set 2:
> 
> > Patch Set 2:
> > 
> > > Patch Set 2:
> > > 
> > > Looks like there's a compilation error in windows, please fix.
> > > 
> > > Also, can pbos@ or another owner of webrtc/test please lgtm with a webrtc account instead of a chromium one? :)
> > 
> > I think build error will get resolved once LGTM is received from owners as expected by build script.
> 
> No, this is caused by msvc being more strict when casting between integer types. Click in any of the red windows bots and then check the log from the compilation step (also in red):
> 
> ...
> webrtc\video\video_loopback.cc(268): error C2397: conversion from 'int' to 'uint32_t' requires a narrowing conversion
> ...
> 
> Without looking at the code, I think you'll need an explicit static_cast there.

Erik,
Thanks for your the guidance here!
I have made the required changes, instead of typecasting it to uint32_t I followed little different path. Please check it.

Also formatting/indentation issue is solved.

Patch-set: 3
Reviewer: Tarun Chawla <1211784@3ce6091f-6c88-37e8-8c75-72f92ae8dfba>