Reland of Changed P2PTestConductor to use a separate worker thread.
patchset #1 contains the original cl.
https://codereview.webrtc.org/1859933002/

patchset #2 change the initiating client to accept both kIceConnectionCompleted kIceConnected as a ice state.

The reason for the previous revert was:
Causes P2PTestConductor.LocalP2PTestDtlsTransferCaller to fail on Win dbg.

https://build.chromium.org/p/client.webrtc/builders/Win32%20Debug/builds/7469/steps/peerconnection_unittests/logs/stdio

e:\b\build\slave\win\build\src\webrtc\api\peerconnection_unittest.cc(1221): error: Value of: initiating_client_->ice_connection_state()
  Actual: 2
Expected: webrtc::PeerConnectionInterface::kIceConnectionCompleted
Which is: 3

BUG= webrtc:5426

Review URL: https://codereview.webrtc.org/1863573007